const fs = require('fs');
const path = require('path');

// Flattening the object to a map of Value -> Key
function flatten(obj, prefix = '') {
  let map = {};
  for (let key in obj) {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    if (typeof obj[key] === 'object' && !Array.isArray(obj[key])) {
      Object.assign(map, flatten(obj[key], fullKey));
    } else {
      map[JSON.stringify(obj[key])] = fullKey;
    }
  }
  return map;
}

const commonEN = {
  nav: {
    features: "Features",
    pricing: "Pricing",
    academy: "Academy",
    library: "Library",
    login: "Login",
    getStarted: "Get Started",
    masteryLab: "Mastery Lab",
    aiAssistant: "AI Assistant",
    signUp: "Sign Up",
    logout: "Logout",
    dashboard: "Dashboard",
    home: "Home",
    platform: "Platform",
    assessment: "Assessment",
    about: "About",
    academySub: {
      all: "All Courses",
      quality: "Quality (9001) Courses",
      security: "Security (27001) Courses",
      environmental: "Environmental (14001) Courses",
      health: "Health & Safety Courses"
    },
    aiAssistantSub: {
      home: "AI Assistant Home",
      navigator: "ISO Navigator",
      auditLens: "Audit Lens",
      benchmark: "Benchmark AI"
    }
  },
  footer: {
    rights: "All rights reserved.",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    product: "Product",
    company: "Company",
    legal: "Legal",
    contact: "Contact",
    about: "About",
    blog: "Blog",
    careers: "Careers",
    newsUpdate: "News & Update",
    subscribe: "Subscribe",
    newsletterDisclaimer: "Subscribe our newsletter for future updates, do not worry we do not spam your email address",
    cookiePolicy: "Cookie Policy",
    description: "ISOBrain gives you the tools to navigate ISO standards with clarity. Everything in one place.",
    cta: "Learn more about ISOBrain",
    adminAccess: "Admin Access",
  },
  academy: {
    premiumBadge: "Premium Certification",
    premiumCertification: "PREMIUM CERTIFICATION",
    heading: "Master Any ISO Standard with",
    heroHeading: "Master ISO properly",
    heroDescription: "Most ISO courses give you information. That’s not the hard part. The hard part is understanding what it means, how it applies, and how to use it in real situations without second-guessing yourself. ISOBrain helps you do exactly that.",
    headingHighlight: "AI",
    description: "Video courses, interactive tools, and certification pathways recognized by global professionals.",
    searchPlaceholder: "What standard do you need to learn today?",
    startFree: "Start Free",
    startForFree: "Start For Free",
    passRatePrefix: "Average pass rate with ISOBrain AI:",
    passRateValue: "98%",
    popularCourses: "Popular Courses",
    learningExperience: "Learning Experience",
    whatYouGet: "What You Get",
    all: "All Courses",
    quality: "Quality (9001) Courses",
    security: "Security (27001) Courses",
    environmental: "Environmental (14001) Courses",
    aiMasterclasses: "AI Masterclasses",
    loadingCourses: "Loading Academy Courses...",
    failedLoad: "Failed to load courses.",
    enrolled: "Enrolled",
    proLevel: "Pro Level",
    modules: "Modules",
    aiAssisted: "AI-Assisted",
    verifying: "Verifying...",
    continueLearning: "Continue Learning",
    viewSyllabus: "View Syllabus",
    qualityManagement: "Quality Management Courses",
    infoSecurity: "Information Security Courses",
    envManagement: "Environmental Management Courses",
    healthSafety: "Health & Safety Courses",
    learningTitle: "Everything You Need to Master ISO",
    learningSubtitle: "Our hybrid learning approach combines expert instruction with AI-powered study tools.",
    videoLearning: "Video-Based Learning",
    videoDesc: "High-quality, comprehensive video lessons covering all aspects of ISO standards, from foundational basics to advanced implementation.",
    aiTools: "AI-Powered Tools",
    aiToolsDesc: "Interactive AI tutor, auto-generated summaries, analogies, flashcards, and quizzes designed to accelerate your retention.",
    pathway: "Certification Pathway",
    pathwayDesc: "Structured learning paths that guide you step-by-step toward achieving recognized professional ISO certifications.",
    smartLearning: "Smart Learning",
    aiToolsLesson: "AI Tools for Every Lesson",
    studyGuide: "Study Guide",
    studyGuideDesc: "Key takeaways extracted instantly",
    briefingDoc: "Briefing Doc",
    briefingDocDesc: "Executive summaries of complex clauses",
    smartNotes: "Smart Notes",
    smartNotesDesc: "Auto-generated structured notes",
    analogies: "Analogies",
    analogiesDesc: "Simplified concepts for quick grasping",
    fullExperience: "The Full Academy Experience",
    lessonsPerCourse: "6 Lessons per Course",
    lessonsDesc: "Comprehensive video lessons covering all aspects of the ISO standard",
    aiQuizzes: "AI-Generated Quizzes",
    aiQuizzesDesc: "Test your knowledge after each lesson with dynamic AI quizzes",
    recognizedCert: "Recognized Certificate",
    certDesc: "Receive an industry-recognized certificate upon course completion",
    learningSystemTitle: "A Learning System for ISO Professionals",
    learningSystemSubtitle: "Not just videos. A structured environment to turn ISO knowledge into real application.",
    learningSystemDesc: "Each course is designed around how ISO actually works in practice. You learn the standard and then work on how to apply it.",
    outcomeTitle: "What You Get",
    outcomeDescription: "Every ISOBrain course is designed to give you functional knowledge, not just a certificate.",
    smartLearningSubtitle: "AI-powered tools to help you study smarter.",
    nextStepBadge: "NEXT STEP",
    nextStepHeading: "Start building real ISO confidence.",
    nextStepTitle: "CONTINUE YOUR JOURNEY",
    nextStepSubtitle: "Ready to Test Your Knowledge?",
    nextStepsSubtitle: "Ready to Test Your Knowledge?",
    nextStepDesc: "If you understand the standard, everything else becomes easier. ISOBrain helps you get there faster.",
  },
  library: {
    badge: "AI-Powered Standards Workspace",
    heroBadge: "Work with the standards. Not around them",
    heading: "ISO Standards Library",
    head: "Explore by Management Systems",
    description: "250+ international standards. Chat with AI, audit clauses, and accelerate compliance — all in one workspace.",
    heroDesc: "ISO standards weren’t built for speed. They’re dense, technical, and difficult to navigate when you’re under pressure to get things right. ISOBrain turns them into something you can actually use. Search, explore, and break down standards in seconds, so you can stop digging and start making decisions with confidence.",
    searchPlaceholder: "Search standards, clauses, categories…",
    hint: "Press Ctrl K to focus · Esc to dismiss",
    viewAll: "View",
    chatWithAi: "Open & Chat with AI",
    noStandards: "No standards found",
    tryDifferent: "Try a different search term or category.",
    showAll: "Show All Standards",
    prev: "Prev",
    next: "Next",
    standard: "Standard",
    nextStepTitle: "CONTINUE YOUR JOURNEY",
    nextStepSubtitle: "Ready to Test Your Knowledge?",
    nextStepHeading: "Stop searching. Start understanding",
    nextStepDesc: "ISO standards shouldn’t slow you down. ISOBrain helps you find what matters, understand it clearly, and apply it with confidence",
    nextStepCta: "Start Assessment",
  },
  aiAssistantHome: {
    badge: "Next-Gen Compliance Intelligence Software",
    heading: "Architect of",
    headingHighlight: "Digital Trust",
    description: "Beyond simple automation. The ISOBrain ecosystem uses high-fidelity neural networks to ingest, analyze, and generate your entire ISO framework in real-time.",
    heroHeading: "Your Dedicated ISO Consultant, Powered by AI",
    heroDescription: "Working with ISO often comes down to interpretation. What does this clause mean in your context? How should it be applied? What’s missing? ISOBrain gives you clear, structured answers based on real standards, so you can move forward without second-guessing yourself.",
    protocolExecution: "PROTOCOL EXECUTION",
    protocolSubheading: "ISOBrain follows a structured process to turn fragmented information into usable guidance",
    ingestionTitle: "1. Ingestion",
    ingestionDesc: "Your inputs, documents, or questions are processed in context",
    analysisTitle: "2. Analysis",
    analysisDesc: "Relevant ISO standards, clauses, and relationships are identified and interpreted",
    generationTitle: "3. Generation",
    generationDesc: "You receive structured outputs, including guidance, procedures, or reports you can use",
    neuralEcosystemTitle: "NEURAL ECOSYSTEM",
    neuralEcosystemDesc: "The assistant connects across the ISOBrain ecosystem, so you’re not working with isolated tools. Each module focuses on a different part of the compliance process, from navigation to auditing and benchmarking",
    searchPlaceholder: "Ask the AI to audit a clause...",
    processBtn: "Process",
    securityNote: "Enterprise-grade security. We never train public models on your proprietary data.",
    isoNavigator: "ISO Navigator",
    navigatorCore: "Navigator Core",
    navigatorDesc: "Neural pathfinding for complex regulatory hierarchies.",
    navigatorBtn: "Initialize Sync",
    auditLens: "Audit Lens",
    forensicCore: "Forensic Core",
    auditDesc: "Deep-packet inspection of organizational compliance health.",
    auditBtn: "Deploy Scanner",
    benchmarkAi: "Benchmark AI",
    evaluation: "Evaluation",
    benchmarkDesc: "Compare your organization against the world. Real-time grading and industry-standard cross-mapping.",
    benchmarkBtn: "Run Assessment",
    isoLibrary: "ISO Library",
    knowledgeBase: "Knowledge Base",
    libraryDesc: "Access every major ISO standard and regulatory framework. Your centralized compliance archive.",
    libraryBtn: "Browse Standards",
    secureData: "SECURE DATA",
    neuralEngine: "NEURAL ENGINE",
    genAiNative: "GENAI NATIVE",
    isoCompliant: "ISO COMPLIANT",
    analyzing: "Analyzing Standard...",
    analyzingDesc: "Our AI is currently processing your request against the latest ISO frameworks. Create a free account to view your generated compliance response.",
    createAccount: "Create Free Account",
    returnHome: "Return to Home",
    faqBadge: "Support Center",
    faqTitle: "Frequently Asked",
    faqHighlight: "Questions",
    faqSubtitle: "Can't find an answer?",
    faqLink: "Talk to our team.",
    faqs: {
      q1: "What can I use the AI Assistant for?",
      a1: "You can use it to interpret ISO clauses, explore requirements, and work through compliance scenarios in context. It’s designed to support day-to-day tasks, from answering specific questions to helping you structure processes and documentation.",
      q2: "How does the assistant generate its responses?",
      a2: "ISOBrain follows a structured process that ingests your input, analyses relevant ISO standards, and generates outputs based on those relationships. This allows it to return guidance that is both contextual and aligned with the standard",
      q3: "What kind of outputs can it generate?",
      a3: " Depending on your input, it can generate explanations, structured summaries, procedures, audit insights, and compliance-related guidance. Outputs are designed to be usable within your workflow, not just informational.",
      q4: "Can I use it with my own inputs or scenarios?",
      a4: "Yes. You can input questions, scenarios, or supporting material, and the assistant will process them in context alongside ISO standards to generate relevant outputs.",
      q5: "Which ISO standards does it support?",
      a5: "The assistant works across multiple ISO frameworks, including quality, security, environmental, and safety standards. Coverage continues to expand as the ISO compliance platform evolves.",
      q6: " How should I use the AI Assistant in my workflow?",
      a6: "Use it as a working tool alongside your existing processes. It helps you interpret requirements, explore gaps, and generate structured outputs as you move through compliance tasks."
    },
    promptQuality: "Quality (9001) Courses",
    promptSecurity: "Security (27001) Courses",
    promptEnvironmental: "Environmental (14001) Courses",
    promptHealth: "Health & Safety Courses",
    promptInfoSec: "Information Security Policy",
  },
  isoNavigator: {
    badge: "Neural Data Architect",
    heading: "Generative AI Consultant for",
    headingHighlight: "ISO Systems",
    description: "Establish, implement, and effortlessly maintain your ISO Management Systems (IMS) with our dedicated virtual consultant.",
    navCore: "NAVIGATION",
    core: "CORE",
    subHeading: "Map your ISO system from the inside out.",
    heroDesc: "ISO standards don’t exist in isolation. ISO Navigator helps you define your organisation, understand requirements in context, and build a structured view of your management system from the ground up",
    dataGenerator: "Data Generator",
    orgContext: "Organization Context",
    isoStandards: "ISO Standards",
    outputStyle: "Desire Output & Style",
    describeOrg: "Describe your organization...",
    describeStandard: "e.g., ISO 27001:2022",
    suggestions: "Suggestions:",
    continue: "Continue",
    process: "Process",
    back: "Back",
    generateDoc: "Generate Document",
    generating: "Generating...",
    newGeneration: "Start New Generation",
    awaitingInput: "Awaiting Input",
    awaitingInputDesc: "Configure your organization details to initialize the Generative AI Consultant.",
    neuralQuery: "Neural Query Engine",
    initProtocolNote: "Initialize protocol for contextual analysis",
    chatPlaceholder: "Ask the AI anything...",
    loaderTitle: "Generating Your ISO Navigator",
    loaderDesc: "Our AI is crafting personalized ISO documentation and strategies based on your industry.",
    loaderStep1: "Analyzing organization context...",
    loaderStep2: "Selecting ISO standards...",
    loaderStep3: "Generating documentation...",
    tones: {
      professional: "Professional",
      academic: "Academic",
      concise: "Concise",
      friendly: "Friendly"
    },
    languages: {
      english: "English",
      spanish: "Spanish",
      french: "French",
      german: "German"
    },
    searchByCat: "Search by category",
    recommendedIso: "Recommended ISO Standards",
    fetchingRecs: "Fetching recommendations...",
    noSugFound: "No suggestions found",
    viewDetails: "View details",
    architectingProtocol: "Architecting Protocol",
    aiStructuring: "AI is structuring compliance documentation based on neural data analysis.",
    match: "Match",
    mappedProtocols: "Mapped ISO Protocols",
    selectedStandard: "SELECTED STANDARD",
    clickToEdit: "Click to edit",
  },
  auditLens: {
    badge: "Forensic Audit Interface",
    heading: "ISO",
    headingHighlight: "Audit Lens",
    description: "Intelligent audit management powered by Generative AI. Planning, execution, and reporting across all ISO standards.",
    forensicInterface: "FORENSIC AUDIT INTERFACE",
    breakDown: "See where your ISO system breaks down.",
    heroDesc: "ISO audit software that helps you identify gaps, inconsistencies, and risks across your ISO system before they become real problems. Plan, review, and assess your compliance with structured, AI-supported analysis.",
    defineOrg: "Define your organisation.",
    workspace: "Audit Workspace",
    stage: "Audit Stage",
    auditStage: "Audit Stage",
    scope: "Forensic Scope",
    forensicScope: "Forensic Scope",
    details: "Material Details",
    materialDetails: "Material Details",
    describeStage: "e.g., Q1 Compliance Audit",
    describeScope: "Identify audit target...",
    identifyTarget: "Identify audit target...",
    materialType: "Material Type",
    selectArtifact: "Select Audit Artifact",
    findings: "Previous Findings (Optional)",
    previousFindings: "Previous Findings (Optional)",
    findingsPlaceholder: "Paste findings from previous audits here...",
    initialize: "Initialize",
    generate: "Generate Material",
    scanning: "Scanning Protocols",
    scanningDesc: "Neural engine is analyzing organizational records for compliance resolution.",
    readyForScan: "Ready for Scan",
    readyForScanDesc: "Initialize your audit stage and scope to activate the forensic analytical engine.",
    diagnosticQuery: "Diagnostic Query",
    activateNote: "Activate forensic engine for contextual resolution",
    activateForensicNote: "Activate forensic engine for contextual resolution",
    chatPlaceholder: "Ask about your generated audit material...",
    chatPlaceholderActive: "Ask about your generated audit material...",
    chatPlaceholderGeneral: "Ask anything about ISO audit practices...",
    loaderTitle: "Forging Audit Materials",
    loaderDesc: "Our AI is generating technical audit documents tailored to your organizational scope.",
    loaderStep1: "Planning audit scope...",
    loaderStep2: "Analyzing requirements...",
    loaderStep3: "Generating documentation...",
    stages: {
      s1: { title: "Stage 1: Planning", sub: "Defining Scope & Schedule" },
      s2: { title: "Stage 2: Execution", sub: 'The "Lens" in Action' },
      s3: { title: "Stage 3: Reporting", sub: "Turning Data into Insights" },
      s4: { title: "Stage 4: Follow-up", sub: "Closing the Loop" }
    },
    materialTypes: {
      charter: "Audit Charter",
      checklist: "Audit Checklist",
      questionnaire: "Pre-audit Questionnaire",
      ncr: "Non-Conformance Report",
      cap: "Corrective Action Plan"
    }
  },
  benchmarkAi: {
    badge: "Compliance Intelligence Node",
    heading: "ISO",
    headingHighlight: "Benchmark AI",
    description: "Advanced document benchmarking via Neural OCR and Generative AI. Instant compliance scoring and GAP resolution.",
    portal: "ANALYSIS PORTAL",
    seeHowMeasures: "See how your system measures up",
    heroLongDesc: "Benchmark AI analyses your ISO documentation against relevant standards to identify gaps, inconsistencies, and areas for improvement. Understand where you stand, what’s missing, and what to fix next",
    protocolInput: "Protocol Input",
    deployProtocol: "Deploy PDF Protocol",
    ocrEnabled: "Neural OCR Enabled",
    improvementVector: "Improvement Vector",
    improvementPlaceholder: "Describe improvement goals or paste raw data...",
    protocolType: "Protocol Type",
    domain: "Domain",
    suggestedVectors: "Suggested Vectors:",
    hint: "Be specific about the ISO standard and what aspects you want to improve",
    initialize: "Initialize Benchmarking",
    initializeBench: "Initialize Benchmarking",
    secureProcessing: "Secure Neural Processing",
    ocrExtraction: "Multi-Layer OCR Extraction",
    varianceAnalysis: "Compliance Variance Analysis",
    readyForBenchmark: "Ready for Benchmark",
    readyForBenchDesc: "Upload your ISO-related protocols to activate the benchmarking engine. AI will resolve architectural gaps and compliance variance.",
    intelligence: "Compliance Intelligence",
    compIntelligence: "Compliance Intelligence",
    directQueryNote: "Direct query access to ISO requirement matrices",
    matrixNote: "Direct query access to ISO requirement matrices",
    loaderTitle: "Analyzing Your Document",
    loaderDesc: "Please wait while our AI reviews your document for ISO compliance and gap analysis.",
    loaderStep1: "Extracting text via OCR...",
    loaderStep2: "Understanding document context...",
    loaderStep3: "Running gap analysis...",
    loaderStep4: "Generating recommendations...",
    badgeResults: "Compliance Variance Analysis",
    diagHeading: "Diagnostic",
    diagHighlight: "Benchmark Results",
    diagDesc: "Neural analysis complete. Organizational documentation has been cross-referenced against ISO requirement matrices.",
    neuralInput: "Neural Input",
    scanned: "Scanned",
    analyzed: "Analyzed",
    diagReset: "Diagnostic Reset",
    analysisComplete: "Analysis Complete! See results below.",
    analyzeAnother: "Analyze Another Document",
    processedSecurely: "Processed securely",
    ocrTech: "OCR technology",
    isoRequirements: "ISO requirements",
    overallScore: "Overall Score",
    completeness: "Completeness",
    effectiveness: "Effectiveness",
    gradeLabel: "Grade",
    neuralMatrix: "Neural Variance Matrix",
    optimizationRoadmap: "Optimization Roadmap",
    strengths: "Strengths",
    identifiedGaps: "Identified Gaps",
    neuralConsultant: "Neural Consultant",
    benefit: "Benefit",
    conforming: "Conforming",
    majorGap: "Major Gap",
    minorGap: "Minor Gap",
    evidence: "Evidence",
    gap: "Gap",
    chatPlaceholder: "Inquire about optimization steps...",
    recommendation: "Recommendation",
    priority: "Priority",
    describeGoals: "Describe your improvement goals or paste raw data...",
    improvementGoal: "Improvement Goal",
    tip: "Be specific about the ISO standard and what aspects you want to improve.",
  },
  mastery: {
    badge: "ISO Assessment Tool",
    heroHeading: "AI MASTERY LAB",
    heroSubtitle: "Where do you stand on ISO? Find your gaps in minutes.",
    heading: "Train Your ISOBrain Mastery",
    headingHighlight: "5 minutes.",
    headingPrefix: "Find your compliance gaps in",
    description: "Test your knowledge of ISO standards based on your specific industry, role, and department so you can proactively upskill  and earn a verifiable Certificate of Competency.",
    cta: "Start Your Free Assessment",
    info1: "Takes 10 minutes",
    info2: "Personalized AI feedback",
    info3: "Used by 5,000+ Auditors",
    infoPersonalized: "Personalised feedback",
    infoProfessionals: "Used by ISO professionals",
    configTitle: "CONFIGURE YOUR ASSESSMENT",
    loaderTitle: "Generating Your Exam",
    loaderDesc: "Our AI is crafting personalized ISO questions based on your industry and role.",
    loaderStep1: "Analyzing your profile...",
    loaderStep2: "Selecting ISO standards...",
    loaderStep3: "Crafting questions...",
    step1Title: "Calibrate",
    step1Desc: "Our AI curates a custom exam tailored to your operational reality.",
    step2Title: "Beat the Clock",
    step2Desc: "You have 15 minutes to answer 30 difficult, multiple-choice questions.",
    step3Title: "Unlock Report",
    step3Desc: "View your Competency Report and targeted resources to close gaps.",
    exploreMore: "Explore More Features",
    nextStepTitle: "Your Next Steps",
    nextStepsTitle: "Your Next Steps",
    nextStepSubtitle: "Continue your journey towards ISO mastery.",
    nextStepsSubtitle: "Continue your journey towards ISO mastery.",
    nextStepDesc: "If you understand the standard, everything else becomes easier. ISOBrain helps you get there faster.",
    card1Title: "ISO Library",
    card1Desc: "Access complete standard texts and matrices.",
    card1Cta: "Browse Library",
    card2Title: "AI Assistant",
    card2Desc: "Chat with our GenAI consultant for instant answers.",
    card2Cta: "Open Assistant",
    card3Title: "ISOBrain Academy",
    card3Desc: "Enroll in comprehensive learning courses.",
    card3Cta: "Start Learning",
    generating: "Generating...",
  },
  review: {
    heading1: "Loved by",
    heading2: "Experts",
    heading3: "Globally",
    subtitle: "Join 5,000+ organizations mastering ISO compliance with ISOBrain.",
    ctaHeading: "Ready to automate your",
    ctaHighlight: "ISO Compliance?",
    ctaButton: "Get Started for Free",
    ctaDescription: "Join thousands of compliance professionals using ISOBrain to navigate ISO standards, reduce audit risk, and build systems that work.",
    trustBadge: "TRUSTED BY PROFESSIONALS",
    trustSubtitle: "ISO compliance software built for people who need to get it right.",
    trustDesc: "When you’re working with ISO, there’s no room for guesswork. That’s why ISOBrain is used by compliance teams, auditors, and professionals who need clear answers, structured guidance, and confidence in their decisions.",
    readyStand: "Ready to see where",
    readyStandHighlight: "you stand?",
    readyStandDesc: "You don’t need another tool. You need clarity on what’s working, what’s missing, and what to do next. That’s exactly what ISOBrain gives you.",
    startFreeAssessment: "Start Your Free Assessment",
    reviews: [
      {
        name: "Devid Miller",
        role: "Senior Lead Auditor",
        comment: "ISOBrain has transformed how we approach ISO 27001. The AI Assistant identifies gaps in seconds that used to take our team days of manual review."
      },
      {
        name: "Sarah Jones",
        role: "Compliance Director",
        comment: "The most sophisticated ISO tool I've used in 15 years. The Academy ensures my team actually understands compliance rather than just checking boxes."
      },
      {
        name: "Michael Chen",
        role: "QHSE Manager",
        comment: "A game-changer for integrated management systems. The competency benchmarking helped us identify critical risks before our last major audit."
      },
      {
        name: "Emma Wilson",
        role: "ISO Consultant",
        comment: "The accuracy of the AI is remarkable. It understands the nuances of various standards perfectly, making it an indispensable partner for my consultancy."
      }
    ]
  },
  pricingPage: {
    title: "PRICING",
    heading: "Choose the right level of access for your ISO workflow",
    subtitle: "ISOBrain gives you structured tools to navigate standards, assess compliance, and build systems with clarity. Choose the level that matches how you work",
    oneTimeNote: "One-time payment • Full access for 1 month",
    startAssessment: "Start Your Free Assessment",
    buttonText: "One-Time Payment • AI Units Valid for 1 Month",
    monthly: "Monthly",
    annual: "Annual",
    save: "Save 20%",
    priceNote: "Pricing in USD • Cancel Anytime",
    startNow: "Start Now",
    getFullAccess: "Get Full Access",
    purchased: "Purchased",
    was: "Was",
    oneTime: "one-time",
    planDetails: {
      plus: [
        { boldText: "Unlimited ISO Library:", normalText: "Quality, Security, Safety, etc." },
        { boldText: "ISO Mastery Lab:", normalText: "Competency analysis & reports." },
        { boldText: "Global Benchmarking:", normalText: "Tailored for your industry." },
        { boldText: "CPD Certification:", normalText: "Earn verified professional credits." },
        { boldText: "Forever Access:", normalText: "Keep saved content indefinitely." }
      ],
      pro: [
        { boldText: "Everything in Plus" },
        { boldText: "ISOBrain Academy:", normalText: "Context-aware AI learning." },
        { boldText: "Expert Video Lessons:", normalText: "High-quality ISO tutorials." },
        { boldText: "Advanced Study Tools:", normalText: "Master standards faster." },
        { boldText: "Personalized Reports:", normalText: "Deeper skill insights." }
      ],
      ultra: [
        { boldText: "Everything in Pro" },
        { boldText: "AI Navigator:", normalText: "Map through complex clauses." },
        { boldText: "AI Audit Lens:", normalText: "Streamline your auditing process." },
        { boldText: "Benchmark AI:", normalText: "Compare against best practices." },
        { boldText: "Unlimited AI Assistant:", normalText: "Your intelligent companion." }
      ]
    },
    compareAll: "Compare all features",
    hideDetails: "Hide feature details",
    coreCapabilities: "Core Capabilities",
    starter: "Starter",
    pro: "Pro",
    enterprise: "Enterprise",
    limited: "Limited",
    unlimited: "Unlimited",
    feature1: "ISO Standard Access",
    feature2: "AI Navigator Assistant",
    feature3: "Forensic Audit Lens",
    feature4: "Benchmark AI Evaluator",
    feature5: "Custom Industry Path",
    feature6: "Priority Cloud Support",
    feature7: "Multi-User Workspace",
    initializing: "Initialising Secure Access...",
    analysisPortal: "Analysis Portal",
    compIntelligence: "Compliance Intelligence",
    describeGoals: "Describe your improvement goals or paste raw data...",
    directQueryNote: "Direct query access to ISO requirement matrices",
    improvementGoal: "Improvement Goal",
    initializeBench: "Initialize Benchmarking",
    readyForBench: "Ready for Benchmark",
    readyForBenchDesc: "Upload your ISO protocols to activate the benchmarking engine.",
    tip: "Be specific about the ISO standard and what aspects you want to improve.",
    description: "Whether you're a compliance officer, auditor, quality manager, or consultant, ISOBrain has a plan designed to help you navigate standards, learn with AI, and assess your competence. Simple Pricing: One-Time Payment, One Month of Access.",
    oneTime: "One-Time Payment • AI Units Valid for 1 Month",
    cta: "Get Full Access",
    simplePricing: "Simple Tiered Pricing",
    days: "Days Access",
  },
  faq: {
    badge: "Support Center",
    heading1: "Point-of-Sale",
    heading2: "Clarifications",
    subtitle: "Quick answers to the most common objections. If you need more help, our team is standing by 24/7.",
    q1: "How does the billing work? Is it a subscription?",
    a1: "No, there are no hidden subscriptions or auto-renewals. You make a one-time payment for the package of your choice, which gives you unlimited access to those features for exactly one month.",
    q2: "What happens to my work when my one-month access ends?",
    a2: "Your work is yours to keep! You can save any content generated on ISOBrain.ai during your active month. Once your one-month access expires, you will still be able to log in to view, manage, and access all your saved content—you can even access it offline!",
    q3: "Is there a free trial available?",
    a3: "Yes! You can create a free account to explore the platform, browse the ISO Library outlines, and see how our tools work before making your one-time payment for a Plus, Pro, or Ultra package.",
    q4: "Who is ISOBrain designed for?",
    a4: "ISOBrain is built for all ISO professionals, including Compliance Officers, Auditors, HR Managers, Quality Managers, Implementers, and Consultants.",
    q5: "What exactly can the AI Assistant (Ultra Plan) do for me?",
    a5: "Our proprietary AI Assistant is designed to save you hours of manual work. It acts as a smart search engine for complex clauses (Navigator), reviews documentation to identify potential non-conformities (Audit Lens), and compares your processes against industry global standards (Benchmark AI).",
    q6: "How does the ISO Mastery Lab work?",
    a6: "The Mastery Lab is a premier structured assessment platform. Choose your industry and job role, take the assessment, and receive a personalized skill report with AI-driven insights.",
  },
  auth: {
    loginTitle: "Welcome Back",
    enterpriseVerified: "Enterprise Verified",
    enterCredentials: "Enter your credentials to access your workspace.",
    emailAddress: "Email Address",
    password: "Password",
    forgotPassword: "Forgot?",
    signIn: "Sign in",
    signingIn: "Signing in...",
    continueWithGoogle: "Continue with Google",
    or: "or",
    newToIsobrain: "New to ISOBrain?",
    createAccount: "Create account",
    loginWithMicrosoft: "Log in with Microsoft",
    intelligenceFirst: "Intelligence First Compliance",
    secureAccessTitle: "Securely Access Your AI Compliance Engine.",
    seamlessSeamless: "Managing standards across global teams has never been this seamless.",
    privacyPolicy: "PRIVACY POLICY",
    termsOfService: "TERMS OF SERVICE",
    signUpTitle: "Initialize Your Account",
    joinEcosystem: "Join 5,000+ organizations mastering compliance with ISOBrain.",
    fullName: "Full Name",
    alreadyHaveAccount: "Already have an account?",
    logIn: "Log in",
    initializeSync: "Initialize Sync",
    initializing: "Initializing...",
    enterpriseGrade: "Enterprise Grade Compliance",
    revISOIntelligence: "Revolutionizing ISO Standards with Intelligence.",
    joinEnterprises: "Join 500+ enterprises automating their compliance workflows with ISOBrain's proprietary AI engine.",
    sarahJenkinsTestimonial: '"ISOBrain transformed our audit process from weeks to hours."',
    sarahJenkinsTitle: "— Sarah Jenkins, Head of Compliance at Vercel",
    identityVerified: "Identity Verified",
    welcomeToIsobrain: "Welcome to ISOBrain",
    freeTrial: "Start your 7-day free trial. No credit card required.",
    workEmailAddress: "Work Email Address",
    authenticating: "Authenticating...",
    continueEnterpriseSSO: "Continue with Enterprise SSO",
    otpTitle: "Verification Required",
    otpSubtitle: "We've sent a high-fidelity sync code to your email. Enter it below to initialize your neural workspace.",
    digitCode: "6-Digit Sync Code",
    verifyAccount: "Verify Account",
    didntReceiveCode: "Didn't receive the code?",
    resendSyncCode: "Resend Sync Code",
    checkEmail: "Check your email",
    sentCodeTo: "We have sent a 6-digit verification code to",
    invalidCode: "Invalid or expired verification code. Please try again.",
    verifyEmail: "Verify Email",
    verifying: "Verifying...",
    clickToResend: "Click to resend",
    byContinuing: "By continuing, you agree to our",
    and: "and",
    loadingVerification: "Loading verification...",
    neuralSyncActive: "Neural Sync Active",
    secureHandshake: "Initializing Secure Handshake",
    loadingEnvironment: "Our AI is preparing your isolated compliance environment. This usually takes 5-10 seconds.",
    authenticatingNode: "Authenticating Node...",
    preparingWorkspace: "Preparing Neural Workspace...",
    finalizingHandshake: "Finalizing Secure Handshake...",
  },
  hero: {
    badge: "Next-Gen ISO Compliance Software",
    heading1: "Train Your ISOBrain",
    heading2: "on",
    typewriterWords: ["ISO 9001?", "ISO 27001?", "ISO 14001?", "Compliance?"],
    description: "Take our ultimate AI-driven ISO competency assessment. Uncover your blind spots before they turn into costly audit failures.",
    subheadline: "ISO compliance shouldn’t feel like a maze of documents, audits, and second-guessing. ISOBrain shows you exactly where you stand, what’s missing, and what to do next, in minutes",
    seeHowItWorks: "See How It Works",
    socialProof: "Used by compliance teams, auditors, and ISO professionals worldwide",
    emailPlaceholder: "Enter work email",
    cta: "Start for Free",
    watchDemo: "Watch Demo",
    noCreditCard: "No Credit Card Required",
    trustedBy: "Trusted by",
    trustedCount: "10,000+",
    trustedRole: "Compliance Officers & Auditors globally",
  },
  aboutPage: {
    badge: "ABOUT ISOBRAIN’S ISO COMPLIANCE SOFTWARE",
    heading: "Rethinking ISO Compliance",
    heroHeading: "ISO, without the confusion.",
    description: "ISO standards are powerful. But working with them rarely feels that way. Most professionals don’t struggle because they lack ability. They struggle because the standards are dense, fragmented, and difficult to apply in real-world situations. ISOBrain was built to change that.",
    problemTitle: "THE PROBLEM",
    problemText: "For years, ISO has lived in documents, spreadsheets, and disconnected systems. You read the standard. Interpret it yourself. Apply it as best you can. Then hope it holds up under audit. It’s slow. It’s unclear. And it leaves too much room for doubt. ISOBrain changes how you work with ISO. Instead of digging through documentation or relying on static training, you get a system that shows you exactly where you stand, what’s missing, and how to move forward. It connects learning, assessment, and real-world application into one place. So you’re not just learning the standard. You’re working with it.",
    solutionText: "ISOBrain changes that by bringing active AI intelligence into every step of your compliance journey.",
    cta: "Explore the Platform",
    systemHeading: "A system, not another tool.",
    systemSubheading: "ISOBrain brings together four core parts of the ISO process:",
    systemTitle: "Core Ecosystem",
    systemSubtitle: "Four pillars designed to transform how you interact with ISO standards.",
    assessmentTitle: "Assessment",
    learningTitle: "Learning",
    guidanceTitle: "Guidance",
    applicationTitle: "Application",
    assessment: "Understand your current level and identify gaps",
    learning: "Build knowledge through structured, practical content",
    guidance: "Get answers and direction when you need them.",
    application: "Turn standards into real, working processes.",
    whoTitle: "Who It’s For",
    whoSubtitle: "Our ISO compliance software is used by",
    whoItems: [
      "Compliance professionals",
      "Quality managers",
      "Auditors",
      "Operations teams"
    ],
    whoFinal: "People who don’t just need to understand ISO, but need to apply it, maintain it, and stand behind it.",
    who1: "Compliance professionals",
    who2: "Quality managers",
    who3: "Auditors",
    who4: "Operations teams",
    whoDesc: "If you interact with ISO standards, ISOBrain is your competitive advantage.",
    approachTitle: "Our Approach",
    approachText: "We don’t believe in adding more complexity. Every part of ISOBrain is built to simplify how you work, reduce time spent searching, and give you confidence in your decisions. Because when you understand what you’re doing, everything moves faster.",
    ctaFinal: "Start Your Journey"
  },
  platform: {
    heading1: "The Complete",
    heading2: "ISO Ecosystem",
    heading: "The Complete ISO Ecosystem.",
    subheading: "A unified AI-driven platform built to empower compliance officers, auditors, and management professionals.",
    description: "Most ISO compliance tools focus on one part of the process. Learning. Documentation. Audits. ISOBrain connects all of it. So instead of jumping between platforms, guessing your next step, or working things out as you go, you have one clear system that shows you what to do, when to do it, and why it matters.",
    moreAboutUs: "More About Us",
    cta: "Learn more about ISOBrain",
    aiAssistant: {
      title: "AI ASSISTANT",
      description: "Get answers when you need them. Stop digging through documents or second-guessing your interpretation. Ask a question and get a clear, structured answer based on real ISO standards. Whether you’re working through a clause, preparing for an audit, or building a process, you’ll get guidance you can actually use.",
      btn: "Explore AI Assistant",
    },
    academy: {
      title: "ISO ACADEMY",
      description: "Learn it properly. Apply it confidently.Most courses stop at theory. ISOBrain shows you how it works in practice. Structured learning paths, real-world examples, and interactive compliance tools for enterprises and individuals. Understand the standard and apply it in your day-to-day work without getting stuck",
      btn: "Start Learning",
    },
    masteryLab: {
      title: "MASTERY LAB",
      description: "See your gaps. Fix them fast.You can’t improve what you can’t see. ISOBrain assesses your knowledge based on your role and responsibilities, then shows you exactly where you’re falling short. No guesswork. No wasted time. Just a clear path forward. ",
      btn: "Test Your Knowledge",
    },
    library: {
      title: "ISO LIBRARY",
      description: "Work with the standards, not around them.Access ISO standards in a way that actually makes sense. Search, explore, and break down complex clauses into something you can understand and act on without getting lost in pages of documentation.",
      btn: "Access Library",
    },
  },
};

const valueToKeyMap = flatten(commonEN);

function processFile(filePath) {
  // Skip files that have been manually adjusted to avoid breaking complex logic
  const fileName = path.basename(filePath);
  if (['ResultPage.tsx', 'GetStartedSection.tsx'].includes(fileName)) {
    return;
  }

  let content = fs.readFileSync(filePath, 'utf8');
  let changed = false;

  const sortedValues = Object.keys(valueToKeyMap).sort((a, b) => b.length - a.length);

  for (const jsonVal of sortedValues) {
    const key = valueToKeyMap[jsonVal];
    const rawVal = JSON.parse(jsonVal);

    // Replace {"Value"} with {t('key')}
    const bracedJson = `\{${jsonVal}\}`;
    if (content.includes(bracedJson)) {
      content = content.split(bracedJson).join(`{t('${key}')}`);
      changed = true;
    }

    // Replace attribute="Value" with attribute={t('key')}
    // Improved regex to avoid matching === or other non-attribute assignments
    const attrRegex = new RegExp(`(?<![=!])=\\s*${jsonVal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'g');
    if (attrRegex.test(content)) {
      content = content.replace(attrRegex, `={t('${key}')}`);
      changed = true;
    }

    // Replace >Value< with >{t('key')}<
    if (typeof rawVal === 'string') {
      const escapedRaw = rawVal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const textRegex = new RegExp(`>\\s*${escapedRaw}\\s*<`, 'g');
      if (textRegex.test(content)) {
        content = content.replace(textRegex, `>{t('${key}')}<`);
        changed = true;
      }
    }

    // Handle arrays specifically for things like typewriterWords
    if (Array.isArray(rawVal)) {
      const escapedArray = jsonVal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const arrayRegex = new RegExp(`${escapedArray}`, 'g');
      if (arrayRegex.test(content)) {
        content = content.replace(arrayRegex, `t('${key}', { returnObjects: true })`);
        changed = true;
      }
    }
  }

  if (changed) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`Restored i18n in ${filePath}`);
  }
}

function walkDir(dir) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);
    if (stat.isDirectory()) {
      if (['node_modules', '.git', '.next', 'i18n'].includes(file)) continue;
      walkDir(fullPath);
    } else if (file.endsWith('.tsx') || file.endsWith('.ts')) {
      processFile(fullPath);
    }
  }
}

walkDir(path.resolve('c:/front-end-web/frontend/scalafrodriguez-front_end'));
console.log("Done");
